TWRP_DEVICE="on7xreflte"

# Common
export ALLOW_MISSING_DEPENDENCIES=true
export LC_ALL="C"

# Fix platform version for TWRP 12.1
export PLATFORM_VERSION="12.1.0"
export PLATFORM_VERSION_LAST_STABLE="12.1.0"
export PLATFORM_SECURITY_PATCH="2099-12-31"
export TARGET_PLATFORM_VERSION="SPL1A"

# TWRP specific
export LZMA_RAMDISK_TARGETS="recovery"